name = "ValueIteration"
uuid = "485ddabf-8628-49a7-9e47-2c80b05bea31"
authors = ["Abhinav Bhatia <abhinav.bhatia.me@gmail.com>"]
version = "0.2.0"

[deps]
MDPs = "11f886ef-95cd-43ae-b218-d50c093ca059"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
